### ISSUE TITLE
Divide docs into subpages

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-framework.github.io#1]
Someone who knows Jekyll better than myself could structure that page nicer. I would like to have three menu-linked pages leading to the three building blocks (format, tools, repo).

**Comment by maxibor** [comment]
This would first involve to change the Cayman theme (one page theme) to another Jekyll theme line one of [these](https://jekyllthemes.io/jekyll-documentation-themes)

**Comment by stschiff** [comment]
I thought about docsy, but it's important that this webpage can host static files as well (such as the `terms.rdf.jsonld` file from the poseidon-scheme repo, so if docsy can do that I'm all fine, otherwise also happy to change to a different scheme. Feel free to make a suggestion.

**Comment by maxibor** [comment]
[Docsy](https://github.com/vsoch/docsy-jekyll) is a Jekyll/Hugo theme. [Docsify](https://docsify.js.org/#/) is the framework.
Docsify (which we used for the RRDM-SHH workshop) is also nice and allows for static files as well (for example: [https://rrdm-shh.github.io/day1/20200129_MPG_SHH_workshop_GerlachR.pdf](https://rrdm-shh.github.io/day1/20200129_MPG_SHH_workshop_GerlachR.pdf))

Both Jekyll with a Documation (like Docsy for example) theme, or Docsify would be good choices IMO. 
But because Docsify doesn't need a backend (it's all Javascript running in the user's browser), there are less things that could break because of a bad commit.

**Comment by stschiff** [comment]
Oh I see. Well, that sounds all good then. Happy to go with either Jekyll/Docsy or docsify. Would be great if you could initiate the move!
